name: Git LFS Pull
description: Pull from LFS, always use commaai/openpilot

runs:
  using: composite
  steps:
    - shell: bash
      run: |

        # BUG: actions/checkout lfs = true don't work

        git lfs pull

        # check a model exists and is not a pointer
        model=selfdrive/modeld/models/driving_policy.onnx
        [[ -f $model ]] || {
          echo "::error::model $model not found"
          exit 1
        }
        if head -1 $model | grep -q git-lfs; then
          echo "::error::model $model is an lfs pointer"
          exit 1
        fi
