name: Nix Build

on:
  push:
    branches:
      - master
      # TOGO: for dev
      - nixify*
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      run_number:
        default: '1'
        required: true
        type: string

# TOGO: for dev
# concurrency:
#   group: tests-ci-run-${{ inputs.run_number }}-${{ github.event_name == 'push' && github.ref == 'refs/heads/master'
#     && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name
#     }}
#   cancel-in-progress: true

env:
  AZURE_TOKEN: ${{ secrets.AZURE_COMMADATACI_OPENPILOTCI_TOKEN }}
  PACKAGE: default
  NIX: nix --print-build-logs --show-trace
  # NIX_CONFIG: |
  #   builders =
  #   eval-store = auto
  #   experimental-features = nix-command flakes
  #   max-jobs = 2
  #   store = ssh-ng://eu.nixbuild.net
  # can't reference $NIX or ${{ env.nix }}, so below must match NIX above
  NIX_DEVELOP_COMMAND: nix --print-build-logs --show-trace develop path:. --command
  PYTEST: pytest --continue-on-collection-errors --durations=0 -n logical
  PYTHONWARNINGS: error
  SHELLOPTS: xtrace

# XXX: github support yaml anchors, but do NOT support merge keys (<<:) so we have to
# break DRY - all jobs (apart from static_analysis which doesn't need submodules and
# uses a separate build cache) MUST match build_release
# TODO: All jobs from ./tests.yaml
jobs:

  # build:
  #   uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v24
  #   secrets:
  #     nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
  #   with:
  #     filter_builds: .system | contains("darwin") | not
  #  # make nix ignore git - important for lfs
  #     flake: path:.
  #     lfs: true
  #     nix_conf: |
  #       accept-flake-config = true
  #       download-buffer-size = 268435456
  #       http-connections = 128
  #       keep-derivations = true
  #       keep-outputs = true
  #       max-substitution-jobs = 64
  #       ${{ inputs.nix_config }}
  #     nix_on_tmpfs: true
  #     nix_version: 2.31.2

  package:
    name: Package
    # needs:
    #   - check
    strategy: &strategy
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          # - macos-15
          # - macos-15-intel
    permissions:
      contents: write
    runs-on: &runs-on ${{ matrix.os }}
    steps:
      - uses: &checkout actions/checkout@v6
        with:
          lfs: true
      - uses: &nix-setup ./.github/workflows/nix-setup
        with: &nix-secrets
          cachix_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
      - uses: &nix-build ./.github/workflows/nix-build
      - name: Verify Reproducible
        uses: *nix-build
        with:
          flags: --rebuild

  shell:
    name: Shell
    strategy: *strategy
    runs-on: *runs-on
    steps:
      - uses: *checkout
      - uses: *nix-setup
        with: *nix-secrets
      - uses: *nix-build
        with:
          package: devShells.SYSTEM.default

  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - uses: *checkout
      - uses: *nix-setup
        with: *nix-secrets
      - shell: bash
        run: $NIX flake check -v path:.

  flake:
    name: Flake
    needs: [check, package]
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: *checkout
      - shell: bash
        run: |
          sed -i 's|\(build-cache\.url\).*| \
            "\1 = github:${{ github.repository }}/${{ github.sha }}";|' \
            flake.nix
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: '[ci] update flake build-cache commit'
          file_pattern: flake.nix

  # build_impure:
  #   name: Build (Impure)
  #   needs: check
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: *os
  #   runs-on: ${{ matrix.os }}
  #   env:
  #     SCONS_CACHE: /var/tmp/scons
  #     SCONS_SYSTEM: scons-$SYSTEM
  #   steps:
  #
  #     - uses: actions/checkout@v6
  #       with:
  #         lfs: true
  #         submodules: true
  #
  #  # scons cache
  #
  #     - shell: bash
  #       run: |
  #         sudo mkdir -p $SCONS_CACHE
  #         sudo chown $USER $SCONS_CACHE
  #
  #     - shell: bash
  #       run: |
  #         echo SCONS_SYSTEM_DATE=${{env.SCONS_SYSTEM }}-$(
  #           git log -1 --pretty=format:%cd --date=format:%Y-%m-%d
  #         ) >> $GITHUB_ENV
  #
  #     - uses: ./.github/workflows/auto-cache
  #       with:
  #         path: ${{ env.SCONS_CACHE }}
  #         key: ${{ env.SCONS_SYSTEM_DATE }}-${{ github.sha }}
  #         restore-keys: |
  #           ${{ env.SCONS_SYSTEM_DATE }}
  #           ${{ env.SCONS_SYSTEM }}
  #
  #     - uses: ./.github/workflows/nix-setup
  #       with:
  #         cachix_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  #         nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
  #         nix_config: extra-sandbox-paths = ${{ env.SCONS_CACHE }}
  #     - uses: ./.github/workflows/nix-build
  #       with:
  #         package: ${{ env.PACKAGE }}.passthru.test
  #         flags: --impure
